apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhtml-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: footballprovtc
  template:
    metadata:
      labels:
        app: footballprovtc
    spec:
      containers:
      - name: footballprovtc
        image: sontungbk85/webcicd:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: webhtml-demo
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000    
  selector:
    app: footballprovtc

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webhtml-demo-ingress
spec:
  rules:
  - host: web.demo
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webhtml-demo
            port:
              number: 80