apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhtml-demo
  namespace: ingress-nginx 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: footballprovtc
  template:
    metadata:
      labels:
        app: footballprovtc
    spec:
      containers:
      - name: footballprovtc
        image: sontungbk85/k8scicd:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webhtml-demo
  namespace: ingress-nginx 
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # Chỉ định NodePort cụ thể    
  selector:
    app: footballprovtc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webhtml-demo-ingress
  namespace: ingress-nginx 
spec:
  rules:
  - host: web.demo
    http:
      paths:
      - path: :30080
        pathType: Prefix
        backend:
          service:
            name: webhtml-demo
            port:
              number: 80
